# Generated by Django 5.0.2 on 2024-03-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0002_alter_task_labels_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='tasks.TaskLabelLinks', to='labels.label', verbose_name='Task labels'),
        ),
    ]
